export const examples = ["landing", "testimonials", "team", "table"] as const;
export type Example = (typeof examples)[number];

const fr = {
  heading: "Que souhaitez-vous créer ?",
  explore: "EXEMPLES À EXPLORER",
  unavailable: "Cette démonstration utilise un prompt prédéfini.",
  attach: "Joindre",
  style: "Style d’écriture",
  send: "Voir l’exemple",
  back: "Revenir aux exemples",
  loading: "Génération des profils Persona…",
  error: "Les profils sont momentanément indisponibles.",
  retry: "Réessayer",
  dataNote:
    "Identités générées par l’API Persona. Le contenu de la section est un exemple de mise en page.",
  cards: {
    landing: {
      title: "Landing page",
      description: "Une boutique portée par des portraits de votre région.",
      prompt:
        "Crée une landing page pour une boutique de mode avec des portraits fictifs de ma région.",
    },
    testimonials: {
      title: "Témoignages",
      description: "Des avis mis en scène avec des profils locaux.",
      prompt:
        "Crée une section de témoignages avec des personnes fictives de ma région.",
    },
    team: {
      title: "Équipe",
      description: "Une grille d’équipe avec noms, rôles et portraits.",
      prompt:
        "Présente une équipe fictive de ma région pour une page À propos.",
    },
    table: {
      title: "Table de profils",
      description: "Des contacts crédibles pour tester une interface CRM.",
      prompt:
        "Remplis une table CRM avec des personnes fictives et leurs lieux de résidence.",
    },
  },
  landing: {
    eyebrow: "La nouvelle collection",
    title: "Des pièces qui vous ressemblent.",
    description:
      "Découvrez une boutique de mode pensée pour chaque style et chaque histoire.",
    action: "Découvrir la collection",
  },
  testimonials: {
    title: "Ils en parlent mieux que nous",
    first:
      "L’expérience est claire dès le premier instant. On comprend rapidement ce que le produit peut apporter à notre équipe.",
    second:
      "Une interface agréable et des détails bien pensés. C’est exactement ce qu’il nous fallait pour avancer.",
    roles: ["Responsable produit", "Designer indépendante"],
  },
  team: {
    title: "Rencontrez l’équipe",
    description: "Les personnes derrière chaque détail du produit.",
    roles: [
      "Fondation & direction",
      "Produit",
      "Design",
      "Ingénierie",
      "Croissance",
      "Expérience développeur",
    ],
    joinTitle: "Envie de nous rejoindre ?",
    joinDescription:
      "Nous aimons travailler avec des gens qui soignent les détails.",
    joinAction: "Voir les postes",
  },
  table: {
    search: "Filtrer par nom ou e-mail…",
    status: "Statut",
    all: "Tous",
    active: "Actif",
    inactive: "Inactif",
    view: "Vue",
    add: "Ajouter",
    name: "Nom",
    email: "E-mail",
    location: "Lieu",
    performance: "Activité",
    balance: "Solde",
    high: "Élevée",
    medium: "Moyenne",
    low: "Faible",
    rows: "Lignes par page",
    of: "sur",
    previous: "Page précédente",
    next: "Page suivante",
    example: "Colonnes de démonstration : statut, activité et solde.",
  },
} as const;

const en = {
  heading: "What would you like to create?",
  explore: "EXAMPLES TO EXPLORE",
  unavailable: "This demo uses a preset prompt.",
  attach: "Attach",
  style: "Writing style",
  send: "See example",
  back: "Back to examples",
  loading: "Generating Persona profiles…",
  error: "Profiles are temporarily unavailable.",
  retry: "Try again",
  dataNote:
    "Identities generated by the Persona API. Section content is a layout example.",
  cards: {
    landing: {
      title: "Landing page",
      description: "A shop brought to life by portraits from your region.",
      prompt:
        "Create a fashion shop landing page with fictional portraits from my region.",
    },
    testimonials: {
      title: "Testimonials",
      description: "Reviews illustrated with local profiles.",
      prompt:
        "Create a testimonials section with fictional people from my region.",
    },
    team: {
      title: "Team",
      description: "A team grid with names, roles and portraits.",
      prompt: "Present a fictional team from my region for an About page.",
    },
    table: {
      title: "Profiles table",
      description: "Believable contacts to test a CRM interface.",
      prompt:
        "Fill a CRM table with fictional people and their places of residence.",
    },
  },
  landing: {
    eyebrow: "The new collection",
    title: "Pieces that look like you.",
    description:
      "Discover a fashion shop made for every style and every story.",
    action: "Explore the collection",
  },
  testimonials: {
    title: "Hear it from them",
    first:
      "The experience feels clear from the first moment. We quickly saw what the product could bring to our team.",
    second:
      "A thoughtful interface with carefully considered details. Exactly what we needed to move forward.",
    roles: ["Product manager", "Independent designer"],
  },
  team: {
    title: "Meet the team",
    description: "The people behind every detail of the product.",
    roles: [
      "Founder & CEO",
      "Product",
      "Design",
      "Engineering",
      "Growth",
      "Developer experience",
    ],
    joinTitle: "Want to join us?",
    joinDescription: "We enjoy working with people who care about the details.",
    joinAction: "View openings",
  },
  table: {
    search: "Filter by name or email…",
    status: "Status",
    all: "All",
    active: "Active",
    inactive: "Inactive",
    view: "View",
    add: "Add user",
    name: "Name",
    email: "Email",
    location: "Location",
    performance: "Activity",
    balance: "Balance",
    high: "High",
    medium: "Medium",
    low: "Low",
    rows: "Rows per page",
    of: "of",
    previous: "Previous page",
    next: "Next page",
    example: "Demo columns: status, activity and balance.",
  },
} as const;

export function useCaseCopy(locale: string) {
  return locale === "fr" ? fr : en;
}
